name: PR preview (deploy to gh-pages/pr-<number>)

permissions:
  contents: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    name: Build & publish PR preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Prepare gh-pages clone
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # clone or init a local gh-pages worktree
          mkdir gh-pages
          cd gh-pages
          git init
          git remote add origin https://x-access-token:${TOKEN}@github.com/${REPO}
          if git ls-remote --exit-code --heads origin gh-pages; then
            git fetch --depth=1 origin gh-pages:gh-pages
            git checkout gh-pages
          else
            git checkout -b gh-pages
            git commit --allow-empty -m "Initial gh-pages"
            git push origin gh-pages
          fi
          cd ..

      - name: Copy site and assets into PR folder
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          set -euo pipefail
          TARGET=gh-pages/pr-${PR_NUM}
          mkdir -p "$TARGET"
          # copy HTML pages
          rsync -a --delete html/ "$TARGET/"
          # also copy common static asset directories so previews include css/js/images
          for d in css js assets; do
            if [ -d "$d" ]; then
              rsync -a --delete "$d" "$TARGET/$d"
            fi
          done

      - name: Commit and push preview to gh-pages
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.number }}
        run: |
          set -euo pipefail
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Publish PR #${PR_NUM} preview" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${REPO} gh-pages

      - name: Print preview URL
        run: |
          echo "PR preview available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.number }}/"
