name: Smoke tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run smoke test
        run: |
          chmod +x scripts/smoke_test.sh
          ./scripts/smoke_test.sh
        env:
          BASE_URL: https://doodlena.github.io/camppeach
